const hospitalNameCorrections = {
  'THE MEDICAL CITY - ORTIGAS': 'THE MEDICAL CITY',
  'ARMED FORCES OF THE PHILIPPINES HEALTH SERVICE COMMAND': 'Victoriano Luna Medical Center (Formerly AFP Medical Center)',
  'ASIAN HOSPITAL AND MEDICAL CENTER': 'Asian Hospital Inc.',
  'SAN JUAN DE DIOS EDUCATIONAL FOUNDATION INC HOSPITAL': 'San Juan De Dios Educational Foundation, Inc.',
  'DILIMAN DOCTORS HOSPITAL': 'Diliman Doctors Hospital, Inc.',
  "MANILA DOCTOR'S HOSPITAL": 'Manila Doctors Hospital',
  'SANTA ANA HOSPITAL - MANILA': 'Sta. Ana Hospital',
  'TRICITY MEDICAL CENTER': 'Tricity Medical Center, Inc.',
  'UNIHEALTH PARANAQUE HOSPITAL': 'Unihealth Parañaque Hospital And Medical Center, Inc.',
  'VICTOR R. POTENCIANO MEDICAL CENTER': 'Dr. Victor R. Potenciano Medical Center',
  'ADVENTIST MEDICAL CENTER - MANILA': 'Adventist Medical Center Manila',
  'DR. JOSE N. RODRIGUEZ MEMORIAL HOSPITAL AND SANITARIUM': 'Dr. Jose N. Rodriguez Memorial Hospital',
  'FATIMA UNIVERSITY MEDICAL CENTER': 'Fatima University Medical Center Corporation',
  'LAS PINAS GENERAL HOSPITAL AND SATELITE TRAUMA CENTER': 'Las Piñas General Hospital & Satellite Trauma Center',
  'MEDICAL CENTER MANILA': 'Medical Center Manila, Inc.',
  'UNIVERSITY OF STO. TOMAS HOSPITAL': 'University Of Santo Tomas Hospital',
  'UNIVERSITY OF THE EAST RAMON MAGSAYASY MEMORIAL MEDICAL CENTER': 'University Of The East Ramon Magsaysay Memorial Medical Center, Inc.',
  'REGION 1 MEDICAL CENTER': 'Region I Medical Center',
  'ILOCOS SUR PROVINCIAL HOSPITAL - GABRIELA SILANG': 'Ilocos Sur Provincial Hospital Gabriela Silang',
  'LORMA MEDICAL CENTER': 'Lorma Medical Center, Inc.',
  'DAGUPAN DOCTORS VILLAFLOR HOSPITAL': 'Dagupan Doctors Villaflor Memorial Hospital, Inc.',
  'ILOCOS TRAINING AND REGIONAL MEDICAL CENTER': null,
  'SOUTHERN ISABELA MEDICAL CENTER': 'Southern Isabela General Hospital',
  'REGION 2 TRAUMA AND MEDICAL CENTER': 'Region II Trauma And Medical Center (Veterans Regional Hospital)',
  'CAGAYAN VALLEY MEDICAL CENTER (CVMC)': 'Cagayan Valley Medical Center',
  'CAUAYAN MEDICAL SPECIALIST HOSPITAL': 'Cauayan Medical Specialists Hospital',
  'CENTRO MEDICO': null,
  'JECSON MEDICAL CENTER': 'Jecsons Medical Center',
  'BATAAN ST. JOSEPH HOSPITAL AND MEDICAL CENTER': 'Bataan St. Joseph Hospital & Medical Center Corp.',
  'DR. PAULINO J GARCIA MEMORIAL RESEARCH AND MEDICAL CENTER': null,
  'PAMPANGA PREMIER MEDICAL CENTER': 'Pampanga Premier Medical Center Inc.',
  'QUALIMED - STA. ROSA HOSPITAL': 'Qualimed Health Network Sta. Rosa',
  'MARY MEDIATRIX MEDICAL CENTER': 'Mary Mediatrix Medical Center, Inc.',
  'ORTIGAS HOSPITAL AND HEALTHCARE CENTER': null,
  'SILANG SPECIALIST MEDICAL CENTER': 'Silang Specialists Medical Center, Inc.',
  'CULION SANITARIUM': 'Culion Sanitarium And General Hospital',
  'LUBANG DISTRICT HOSPITAL': null,
  'DAMIAN PROV HOSPITAL': 'Dr. Damian Reyes Provincial Hospital',
  'ISIAH HOSPITAL': 'Isiah Hospital And Medical Center',
  'PALAWAN MEDICAL MISSION MULTIPURPOSE COOPERATIVE': null,
  'THE MEDICAL CITY ILOILO': 'The Medical City - Iloilo',
  'THE HEALTH CENTRUM HOSPITAL': 'The Health Centrum, Inc.',
  'CHONG HUA HOSPITAL MANDAUE': 'Chong Hua Hospital Mandaue (Formerly Chong Hua Hospital Mandaue & Cancer Center)',
  'GOV. CELESTINO GALLARES MEMORIAL HOSPITAL': 'Governor Celestino Gallares Memorial Hospital',
  'ALLEGIANT REGIONAL CARE HOSPITALS': 'Allegiant Regional Care Hospitals, Inc.',
  'CEBU SOUTH GENERAL HOSPITAL': 'Cebu South General Hospital, Inc.',
  "MACTAN DOCTORS' HOSPITAL": "Mactan Doctors' Hospital, Inc.",
  'SAINT VINCENT GENERAL HOSPITAL': 'St. Vincent General Hospital Cebu, Inc.',
  'ST. ANTHONY MOTHER AND CHILD HOSPITAL': 'Saint Anthony Mother And Child Hospital',
  'CATARMAN DOCTORS HOSPITAL INC.,': 'Catarman Doctors Hospital Inc',
  'ORAS DISTRICT HOSPITAL': null,
  'PNP REGION 8': null,
  'REMEDIOS TRINIDAD ROMUALDEZ HOSPITAL': 'Doña Remedios Trinidad-Romualdez Medical Foundation, Inc. (Formerly: Remedios Trinidad Romualdez Hospital)',
  'MAYOR HILARION A. RAMIRO SR. MEDICAL CENTER': 'Mayor Hilarion A. Ramiro Sr. Medical Center (Formerly Mayor Hilarion A. Ramiro Sr. Regional Training And Teaching Hospital)',
  'MERCY COMMUNITY HOSPITAL INC.': 'Mercy Community Hospital, Inc.',
  'RHU BAROY': null,
  'ST. ELIZABETH HOSPITAL': 'St. Elizabeth Hospital, Inc.',
  'ALLAH VALLEY MEDICAL SPECIALIST INC.': 'Allah Valley Medical Specialists Center, Inc.',
  'DR. ARTURO PINGGOY MEDICAL CENTER': 'Dr. Arturo P. Pingoy Medical Center',
  'JUAN DUYAN MEMORIAL HOSPITAL': null,
  'KAPANGAN RHU': null,
  'LANGIDEN RHU': null,
  'PINES CITY DOCTORS HOSPITAL': "Pines City Doctors' Hospital",
  'PINUKPUK DISTRICT HOSPITAL': null,
  'SAINT LOUIS UNIVERSITY HOSPITAL OF SACRED HEART': 'Slu - Hospital Of The Sacred Heart',
};

export default function hf(str: string): string | null {
  const match = hospitalNameCorrections[str.toUpperCase()];

  return (match) || str;
}
