import ConfirmedCasePatientForeignNationalMetadataRawData from './ConfirmedCasePatientForeignNationalMetadataRawData';

interface ConfirmedCasePatientForeignNationalMetadata {
  raw_data: ConfirmedCasePatientForeignNationalMetadataRawData;
}

export default ConfirmedCasePatientForeignNationalMetadata;
