import ConfirmedCasePatientForeignNationalMetadataRawData from "./ConfirmedCasePatientForeignNationalMetadataRawData";

export default interface ConfirmedCasePatientForeignNationalMetadata {
  raw_data: ConfirmedCasePatientForeignNationalMetadataRawData;
}
