export default [
  "Afghan",
  "Albanian",
  "Algerian",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermuda",
  "Bhutanese",
  "Bolivian",
  "Bosnian - Herzegovinian",
  "Batswana",
  "Bouvet Island",
  "Brazilian",
  "British Indian Ocean Territory",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Cayman Islands",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombian",
  "Comoran",
  "Congolese",
  "Cook Islands",
  "Costa Rican",
  "Ivorian",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Ecuadorean",
  "Egyptian",
  "Salvadoran",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltar",
  "Greek",
  "Greenland",
  "Grenadian",
  "Guadeloupe",
  "Guam",
  "Guatemalan",
  "Guinean",
  "Guinea-Bissauan",
  "Guyanese",
  "Haitian",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduran",
  "Hong Kong",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "I-Kiribati",
  "North Korean",
  "South Korean",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Mosotho",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macao",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Marshallese",
  "Martinique",
  "Mauritanian",
  "Mauritian",
  "Mayotte",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Montserrat",
  "Moroccan",
  "Mozambican",
  "Burmese",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "Dutch",
  "New Caledonia",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niue",
  "Norfolk Island",
  "Macedonian",
  "Northern Mariana Islands",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian Territory, Occupied",
  "Panamanian",
  "Papua New Guinea",
  "Paraguayan",
  "Peruvian",
  "Filipino",
  "Pitcairn",
  "Polish",
  "Portuguese",
  "Puerto Rico",
  "Qatari",
  "Reunion",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Helena",
  "Kittian and Nevisian",
  "Saint Lucian",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Senegalese",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Georgia and the South Sandwich Islands",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Svalbard and Jan Mayen",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "East Timorese",
  "Togolese",
  "Tokelau",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Emirian",
  "British",
  "American",
  "United States Minor Outlying Islands",
  "Uruguayan",
  "Uzbekistani",
  "Vanuatu",
  "Venezuelan",
  "Vietnamese",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Welsh",
  "Western Sahara",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
  "Åland Islands",
  "Bonaire, Sint Eustatius and Saba",
  "Curaçao",
  "Guernsey",
  "Isle of Man",
  "Jersey",
  "Montenegro",
  "Saint Barthélemy",
  "Saint Martin (French part)",
  "Serbian",
  "Sint Maarten (Dutch part)",
  "South Sudan",
  "Kosovo"
];