export default [
  { name: 'Abra', region: 'CAR' },
  { name: 'Agusan del Norte', region: 'REGION_XIII' },
  { name: 'Agusan del Sur', region: 'REGION_XIII' },
  { name: 'Aklan', region: 'REGION_VI' },
  { name: 'Albay', region: 'REGION_V' },
  { name: 'Antique', region: 'REGION_VI' },
  { name: 'Apayao', region: 'CAR' },
  { name: 'Aurora', region: 'REGION_III' },
  { name: 'Basilan', region: 'REGION_IX' },
  { name: 'Bataan', region: 'REGION_III' },
  { name: 'Batanes', region: 'REGION_II' },
  { name: 'Batangas', region: 'REGION_IV_A' },
  { name: 'Benguet', region: 'CAR' },
  { name: 'Biliran', region: 'REGION_VIII' },
  { name: 'Bohol', region: 'REGION_VII' },
  { name: 'Bukidnon', region: 'REGION_X' },
  { name: 'Bulacan', region: 'REGION_III' },
  { name: 'Cagayan', region: 'REGION_II' },
  { name: 'Camarines Norte', region: 'REGION_V' },
  { name: 'Camarines Sur', region: 'REGION_V' },
  { name: 'Camiguin', region: 'REGION_X' },
  { name: 'Capiz', region: 'REGION_VI' },
  { name: 'Catanduanes', region: 'REGION_V' },
  { name: 'Cavite', region: 'REGION_IV_A' },
  { name: 'Cebu', region: 'REGION_VII' },
  { name: 'Compostela Valley', region: 'REGION_XI' },
  { name: 'Cotabato', region: 'REGION_XII' },
  { name: 'Davao del Norte', region: 'REGION_XI' },
  { name: 'Davao del Sur', region: 'REGION_XI' },
  { name: 'Davao Occidental', region: 'REGION_XI' },
  { name: 'Davao Oriental', region: 'REGION_XI' },
  { name: 'Dinagat Islands', region: 'REGION_XIII' },
  { name: 'Eastern Samar', region: 'REGION_VIII' },
  { name: 'Guimaras', region: 'REGION_VI' },
  { name: 'Ifugao', region: 'CAR' },
  { name: 'Ilocos Norte', region: 'REGION_I' },
  { name: 'Ilocos Sur', region: 'REGION_I' },
  { name: 'Iloilo', region: 'REGION_VI' },
  { name: 'Isabela', region: 'REGION_II' },
  { name: 'Kalinga', region: 'CAR' },
  { name: 'La Union', region: 'REGION_I' },
  { name: 'Laguna', region: 'REGION_IV_A' },
  { name: 'Lanao del Norte', region: 'REGION_XII' },
  { name: 'Lanao del Sur', region: 'ARMM' },
  { name: 'Leyte', region: 'REGION_VIII' },
  { name: 'Maguindanao', region: 'ARMM' },
  { name: 'Marinduque', region: 'REGION_IV_B' },
  { name: 'Masbate', region: 'REGION_V' },
  { name: 'Mindoro Occidental', region: 'REGION_IV_B' },
  { name: 'Mindoro Oriental', region: 'REGION_IV_B' },
  { name: 'Misamis Occidental', region: 'REGION_X' },
  { name: 'Misamis Oriental', region: 'REGION_X' },
  { name: 'Mountain Province', region: 'CAR' },
  { name: 'Negros Occidental', region: 'REGION_VI' },
  { name: 'Negros Oriental', region: 'REGION_VII' },
  { name: 'Northern Samar', region: 'REGION_VIII' },
  { name: 'Nueva Ecija', region: 'REGION_III' },
  { name: 'Nueva Vizcaya', region: 'REGION_II' },
  { name: 'Palawan', region: 'REGION_IV_B' },
  { name: 'Pampanga', region: 'REGION_III' },
  { name: 'Pangasinan', region: 'REGION_I' },
  { name: 'Quezon', region: 'REGION_IV_A' },
  { name: 'Quirino', region: 'REGION_II' },
  { name: 'Rizal', region: 'REGION_IV_A' },
  { name: 'Romblon', region: 'REGION_IV_B' },
  { name: 'Samar', region: 'REGION_VIII' },
  { name: 'Sarangani', region: 'REGION_XI' },
  { name: 'Siquijor', region: 'REGION_VII' },
  { name: 'Sorsogon', region: 'REGION_V' },
  { name: 'South Cotabato', region: 'REGION_XI' },
  { name: 'Southern Leyte', region: 'REGION_VIII' },
  { name: 'Sultan Kudarat', region: 'REGION_XII' },
  { name: 'Sulu', region: 'ARMM' },
  { name: 'Surigao del Norte', region: 'REGION_XIII' },
  { name: 'Surigao del Sur', region: 'REGION_XIII' },
  { name: 'Tarlac', region: 'REGION_III' },
  { name: 'Tawi-Tawi', region: 'ARMM' },
  { name: 'Zambales', region: 'REGION_III' },
  { name: 'Zamboanga del Norte', region: 'REGION_IX' },
  { name: 'Zamboanga del Sur', region: 'REGION_IX' },
  { name: 'Zamboanga Sibugay', region: 'REGION_IX' },
  { name: 'Metro Manila', region: 'NCR' },
];
